import { School } from '../school';

export const SCHOOL_STATIC: School[] = [
    {school: "Admiralty Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Ahmad Ibrahim Primary School", availability: 0, registration: 0, size: 240 },
    {school: "Ai Tong School", availability: 0, registration: 0, size: 300 },
    {school: "Alexandra Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Anchor Green Primary School", availability: 0, registration: 0, size: 240 },
    {school: "Anderson Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Ang Mo Kio Primary School", availability: 0, registration: 0, size: 150 },
    {school: "Anglo-Chinese School (Junior)", availability: 0, registration: 0, size: 270 },
    {school: "Anglo-Chinese School (Primary)", availability: 0, registration: 0, size: 240 },
    {school: "Angsana Primary School", availability: 0, registration: 0, size: 120 },
    {school: "Beacon Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Bedok Green Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Bendemeer Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Blangah Rise Primary School", availability: 0, registration: 0, size: 90 },
    {school: "Boon Lay Garden Primary School", availability: 0, registration: 0, size: 240 },
    {school: "Bukit Panjang Primary School", availability: 0, registration: 0, size: 240 },
    {school: "Bukit Timah Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Bukit View Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Canberra Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Canossa Catholic Primary School", availability: 0, registration: 0, size: 120 },
    {school: "Cantonment Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Casuarina Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Catholic High School (Primary Section)", availability: 0, registration: 0, size: 240 },
    {school: "Cedar Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Changkat Primary School", availability: 0, registration: 0, size: 150 },
    {school: "CHIJ (Katong) Primary", availability: 0, registration: 0, size: 200 },
    {school: "CHIJ (Kellock)", availability: 0, registration: 0, size: 200 },
    {school: "CHIJ Our Lady of Good Counsel", availability: 0, registration: 0, size: 150 },
    {school: "CHIJ Our Lady of The Nativity", availability: 0, registration: 0, size: 240 },
    {school: "CHIJ Our Lady Queen of Peace", availability: 0, registration: 0, size: 180 },
    {school: "CHIJ Primary (Toa Payoh)", availability: 0, registration: 0, size: 210 },
    {school: "CHIJ St. Nicholas Girls’ School (Primary Section)", availability: 0, registration: 0, size: 210 },
    {school: "Chongfu School", availability: 0, registration: 0, size: 300 },
    {school: "Chongzheng Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Chua Chu Kang Primary School", availability: 0, registration: 0, size: 240 },
    {school: "Clementi Primary School", availability: 0, registration: 0, size: 240 },
    {school: "Compassvale Primary School", availability: 0, registration: 0, size: 240 },
    {school: "Concord Primary School", availability: 0, registration: 0, size: 240 },
    {school: "Corporation Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Damai Primary School", availability: 0, registration: 0, size: 150 },
    {school: "Dazhong Primary School", availability: 0, registration: 0, size: 180 },
    {school: "De La Salle School", availability: 0, registration: 0, size: 240 },
    {school: "East Spring Primary School", availability: 0, registration: 0, size: 150 },
    {school: "Edgefield Primary School", availability: 0, registration: 0, size: 240 },
    {school: "Elias Park Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Endeavour Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Eunos Primary School", availability: 0, registration: 0, size: 90 },
    {school: "Evergreen Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Fairfield Methodist School (Primary)", availability: 0, registration: 0, size: 270 },
    {school: "Farrer Park Primary School", availability: 0, registration: 0, size: 150 },
    {school: "Fengshan Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Fern Green Primary School", availability: 0, registration: 0, size: 270 },
    {school: "Fernvale Primary School", availability: 0, registration: 0, size: 240 },
    {school: "First Toa Payoh Primary School", availability: 0, registration: 0, size: 120 },
    {school: "Frontier Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Fuchun Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Fuhua Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Gan Eng Seng Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Geylang Methodist School (Primary)", availability: 0, registration: 0, size: 270 },
    {school: "Gongshang Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Greendale Primary School", availability: 0, registration: 0, size: 280 },
    {school: "Greenridge Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Greenwood Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Guangyang Primary School", availability: 0, registration: 0, size: 120 },
    {school: "Haig Girls’ School", availability: 0, registration: 0, size: 180 },
    {school: "Henry Park Primary School", availability: 0, registration: 0, size: 300 },
    {school: "Holy Innocents’ Primary School", availability: 0, registration: 0, size: 270 },
    {school: "Hong Wen School", availability: 0, registration: 0, size: 210 },
    {school: "Horizon Primary School", availability: 0, registration: 0, size: 280 },
    {school: "Hougang Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Huamin Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Innova Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Jiemin Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Jing Shan Primary School", availability: 0, registration: 0, size: 150 },
    {school: "Junyuan Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Jurong Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Jurong West Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Juying Primary School", availability: 0, registration: 0, size: 90 },
    {school: "Keming Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Kheng Cheng School", availability: 0, registration: 0, size: 240 },
    {school: "Kong Hwa School", availability: 0, registration: 0, size: 270 },
    {school: "Kranji Primary School", availability: 0, registration: 0, size: 150 },
    {school: "Kuo Chuan Presbyterian Primary School", availability: 0, registration: 0, size: 240 },
    {school: "Lakeside Primary School", availability: 0, registration: 0, size: 240 },
    {school: "Lianhua Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Maha Bodhi School", availability: 0, registration: 0, size: 330 },
    {school: "Maris Stella High School (Primary Section)", availability: 0, registration: 0, size: 270 },
    {school: "Marsiling Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Marymount Convent School", availability: 0, registration: 0, size: 210 },
    {school: "Mayflower Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Mee Toh School", availability: 0, registration: 0, size: 320 },
    {school: "Meridian Primary School", availability: 0, registration: 0, size: 150 },
    {school: "Methodist Girls’ School (Primary)", availability: 0, registration: 0, size: 210 },
    {school: "Montfort Junior School", availability: 0, registration: 0, size: 120 },
    {school: "Nan Chiau Primary School", availability: 0, registration: 0, size: 300 },
    {school: "Nan Hua Primary School", availability: 0, registration: 0, size: 240 },
    {school: "Nanyang Primary School", availability: 0, registration: 0, size: 390 },
    {school: "Naval Base Primary School", availability: 0, registration: 0, size: 240 },
    {school: "New Town Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Ngee Ann Primary School", availability: 0, registration: 0, size: 240 },
    {school: "North Spring Primary School", availability: 0, registration: 0, size: 210 },
    {school: "North View Primary School", availability: 0, registration: 0, size: 180 },
    {school: "North Vista Primary School", availability: 0, registration: 0, size: 240 },
    {school: "Northland Primary School", availability: 0, registration: 0, size: 240 },
    {school: "Northoaks Primary School", availability: 0, registration: 0, size: 240 },
    {school: "Oasis Primary School", availability: 0, registration: 0, size: 280 },
    {school: "Opera Estate Primary School", availability: 0, registration: 0, size: 150 },
    {school: "Palm View Primary School", availability: 0, registration: 0, size: 240 },
    {school: "Park View Primary School", availability: 0, registration: 0, size: 150 },
    {school: "Pasir Ris Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Paya Lebar Methodist Girls’ School (Primary)", availability: 0, registration: 0, size: 270 },
    {school: "Pei Chun Public School", availability: 0, registration: 0, size: 300 },
    {school: "Pei Hwa Presbyterian Primary School", availability: 0, registration: 0, size: 224 },
    {school: "Pei Tong Primary School", availability: 0, registration: 0, size: 240 },
    {school: "Peiying Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Pioneer Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Poi Ching School", availability: 0, registration: 0, size: 240 },
    {school: "Princess Elizabeth Primary School", availability: 0, registration: 0, size: 200 },
    {school: "Punggol Cove Primary School", availability: 0, registration: 0, size: 250 },
    {school: "Punggol Green Primary School", availability: 0, registration: 0, size: 250 },
    {school: "Punggol Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Punggol View Primary School", availability: 0, registration: 0, size: 280 },
    {school: "Qifa Primary School", availability: 0, registration: 0, size: 240 },
    {school: "Qihua Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Queenstown Primary School", availability: 0, registration: 0, size: 240 },
    {school: "Radin Mas Primary School", availability: 0, registration: 0, size: 200 },
    {school: "Raffles Girls’ Primary School", availability: 0, registration: 0, size: 270 },
    {school: "Red Swastika School", availability: 0, registration: 0, size: 240 },
    {school: "River Valley Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Riverside Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Rivervale Primary School", availability: 0, registration: 0, size: 240 },
    {school: "Rosyth School", availability: 0, registration: 0, size: 270 },
    {school: "Rulang Primary School", availability: 0, registration: 0, size: 270 },
    {school: "Sembawang Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Seng Kang Primary School", availability: 0, registration: 0, size: 240 },
    {school: "Sengkang Green Primary School", availability: 0, registration: 0, size: 270 },
    {school: "Shuqun Primary School", availability: 0, registration: 0, size: 200 },
    {school: "Si Ling Primary School", availability: 0, registration: 0, size: 150 },
    {school: "Singapore Chinese Girls’ School (Primary)", availability: 0, registration: 0, size: 192 },
    {school: "South View Primary School", availability: 0, registration: 0, size: 270 },
    {school: "Springdale Primary School", availability: 0, registration: 0, size: 240 },
    {school: "St. Andrew’s Junior School", availability: 0, registration: 0, size: 240 },
    {school: "St. Anthony’s Canossian Primary School", availability: 0, registration: 0, size: 210 },
    {school: "St. Anthony’s Primary School", availability: 0, registration: 0, size: 210 },
    {school: "St. Gabriel’s Primary School", availability: 0, registration: 0, size: 150 },
    {school: "St. Hilda’s Primary School", availability: 0, registration: 0, size: 270 },
    {school: "St. Joseph’s Institution Junior", availability: 0, registration: 0, size: 240 },
    {school: "St. Margaret’s Primary School", availability: 0, registration: 0, size: 192 },
    {school: "St. Stephen’s School", availability: 0, registration: 0, size: 210 },
    {school: "Stamford Primary School", availability: 0, registration: 0, size: 150 },
    {school: "Tampines North Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Tampines Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Tanjong Katong Primary School", availability: 0, registration: 0, size: 200 },
    {school: "Tao Nan School", availability: 0, registration: 0, size: 360 },
    {school: "Teck Ghee Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Teck Whye Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Telok Kurau Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Temasek Primary School", availability: 0, registration: 0, size: 200 },
    {school: "Townsville Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Unity Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Valour Primary School", availability: 0, registration: 0, size: 220 },
    {school: "Waterway Primary School", availability: 0, registration: 0, size: 280 },
    {school: "Wellington Primary School", availability: 0, registration: 0, size: 240 },
    {school: "West Grove Primary School", availability: 0, registration: 0, size: 180 },
    {school: "West Spring Primary School", availability: 0, registration: 0, size: 210 },
    {school: "West View Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Westwood Primary School", availability: 0, registration: 0, size: 210 },
    {school: "White Sands Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Woodgrove Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Woodlands Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Woodlands Ring Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Xinghua Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Xingnan Primary School", availability: 0, registration: 0, size: 150 },
    {school: "Xinmin Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Xishan Primary School", availability: 0, registration: 0, size: 240 },
    {school: "Yangzheng Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Yew Tee Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Yio Chu Kang Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Yishun Primary School", availability: 0, registration: 0, size: 200 },
    {school: "Yu Neng Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Yuhua Primary School", availability: 0, registration: 0, size: 180 },
    {school: "Yumin Primary School", availability: 0, registration: 0, size: 150 },
    {school: "Zhangde Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Zhenghua Primary School", availability: 0, registration: 0, size: 210 },
    {school: "Zhonghua Primary School", availability: 0, registration: 0, size: 120 }
    ];
    